name = "chai-schitai"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "modules"
main = "./dist/index.html"

[[pages_builds]]
build_command = "npm run build"
build_output_directory = "dist"
